spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: wenbo123
    password: wenbo123
    listener:
      simple:
        acknowledge-mode: manual


rabbitmq:
  queue:
    name: Li.Wen.Bo_queue
server:
  port: 8085